### ISSUE TITLE
Add possibility to modify query in ListAction

### ISSUE THREAD

**Issue by cebe** [Insolita/yii2-fractal#7]
Main reason would be to add a condition to limit visibility of some objects.

`ListAction` class currently provides `$prepareDataProvider` propery, but that one requires to build the whole dataprovider including "parent" condition and includes.

As it is now,  `$prepareDataProvider` is not very useful, I propose to change its behavior to have the dataprovider as second argument and can return a modified or newly created dataprovider.

**Comment by cebe** [comment]
example use case:

```php
$actions['list']['prepareDataProvider'] = function(ListAction $action, JsonApiActiveDataProvider $dataProvider) {
    $dataProvider->query->andWhere([
        'owner_id' => Yii::$app->user->id,
    ]);
};
```

**Comment by Insolita** [comment]
Did you mean, that prepareDataprovider callback should be called here https://github.com/Insolita/yii2-fractal/blob/master/src/actions/ListAction.php#L151   with already prepared dataProvider ?

**Comment by cebe** [comment]
yes

**Comment by Insolita** [comment]
Ok

**Comment by cebe** [comment]
I'll make a PR
